name: Docker build and push

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        required: true
        default: "development"

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure Docker to allow insecure registries
        run: |
          mkdir -p ~/.docker
          echo '{ "insecure-registries": ["192.168.1.10:5000"] }' > ~/.docker/daemon.json

      - name: Verify Docker Insecure Registry Configuration
        run: |
          echo "Checking if the registry is properly set as insecure..."
          docker info | grep -i "Insecure Registries" || echo "Registry configuration not found!"

      - name: Check Registry Connection
        run: |
          ping -c 4 192.168.1.10 || echo "Registry not reachable"

      - name: Build Docker image
        run : |
          docker build -t 192.168.1.10:5000/outdu-config-server-build:latest .

      - name: Login to private registry
        run : |
          docker login -u "admin" -p "dadmin123" 192.168.1.10:5000

      - name: Push Docker image to private registry
        run: |
          docker push 192.168.1.10:5000/outdu-config-server-build:latest
