name: Docker build and push

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        required: true
        default: "development"

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure Docker to allow insecure registries
        run: |
          echo "Setting up Docker insecure registry..."
          sudo mkdir -p /etc/docker
          echo '{ "insecure-registries": ["106.51.73.87:5000"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl daemon-reload
          sudo systemctl restart docker

      - name: Verify Docker Insecure Registry Configuration
        run: |
          echo "Checking if the registry is properly set as insecure..."
          docker info | grep -i "Insecure Registries" || echo "Registry configuration not found!"

      - name: Build Docker image
        run : |
          docker build -t 106.51.73.87:5000/outdu-config-server-build:latest .

      - name: Login to Private Docker Registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login 106.51.73.87:5000 -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin

      - name: Push Docker image to private registry
        run: |
          docker push 106.51.73.87:5000/outdu-config-server-build:latest
